//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopping.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Order_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> ShippingAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<int> ShippingAddress_Id { get; set; }
        public Nullable<int> BillingAddress_Id { get; set; }
        public Nullable<int> OrderStatus_Id { get; set; }
        public Nullable<int> Payment_Id { get; set; }
        public Nullable<int> Shipper_Id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
