//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopping.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant_AttributeValue
    {
        public int PV_Attribute_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> ProductVariant_Id { get; set; }
        public Nullable<int> AttributeValue_Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductVariant ProductVariant { get; set; }
        public virtual AttributeValue AttributeValue { get; set; }
    }
}
