//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopping.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCart_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> SCItem_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ShoppingCartItem ShoppingCartItem { get; set; }
    }
}
